# Generated by Django 5.2.6 on 2025-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('displayName', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=300)),
                ('refresh', models.CharField(max_length=300)),
                ('timeOut', models.IntegerField()),
                ('updatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
