# Generated by Django 5.2.6 on 2025-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
