# Generated by Django 5.2.6 on 2025-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_userdata_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='device_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
