# Generated by Django 5.2.6 on 2025-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_userdata_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='refresh',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='token',
            field=models.TextField(),
        ),
    ]
